spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username: postgres
    password: root



api:
  base:
    url: http://localhost:8080

    logging:
      level:
        org.springframework.web: DEBUG
        org.springframework.web.reactive: DEBUG

